# Generated by Django 5.1.1 on 2024-09-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('coordinates', models.TextField(max_length=300)),
                ('types', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
                ('user_rating', models.FloatField()),
                ('Travel_Distance', models.FloatField()),
                ('Travel_Time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('coordinates', models.TextField(max_length=300)),
                ('types', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
                ('user_rating', models.FloatField()),
                ('Travel_Distance', models.FloatField()),
                ('Travel_Time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('coordinates', models.TextField(max_length=300)),
                ('types', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
                ('user_rating', models.FloatField()),
                ('Travel_Distance', models.FloatField()),
                ('Travel_Time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_lat', models.FloatField()),
                ('Source_lon', models.FloatField()),
                ('traffic', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Source_lat', 'Source_lon'), name='unique_source_location')],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('coordinates', models.TextField(max_length=300)),
                ('types', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
                ('user_rating', models.FloatField()),
                ('Travel_Distance', models.FloatField()),
                ('Travel_Time', models.FloatField()),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation')),
            ],
        ),
    ]
