# Generated by Django 5.1.1 on 2024-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlelocation', '0003_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelocation',
            name='traffic',
        ),
        migrations.AddField(
            model_name='apartments',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='competitor',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='publicservices',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='retails',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='status',
            field=models.CharField(default='default', max_length=25),
        ),
    ]
