# Generated by Django 5.1.1 on 2024-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlelocation', '0004_remove_sourcelocation_traffic_apartments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicservices',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicservices',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicservices',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retails',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retails',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retails',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='Travel_Distance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
    ]
