# Generated by Django 5.1.1 on 2024-09-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlelocation', '0005_alter_apartments_travel_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation'),
        ),
        migrations.AddField(
            model_name='publicservices',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation'),
        ),
        migrations.AddField(
            model_name='retails',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlelocation.sourcelocation'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicservices',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retails',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='Travel_Time',
            field=models.CharField(max_length=10),
        ),
    ]
