# Generated by Django 5.1.1 on 2024-10-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "googlelocation",
            "0007_rename_apartments_hotels_education_residentials_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Toursit",
            new_name="Tourist",
        ),
    ]
