# Generated by Django 5.1.1 on 2024-10-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googlelocation", "0009_alter_competitor_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="education",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="hotels",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="publicservices",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="residentials",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="retails",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="supermarket",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tourist",
            name="coordinates",
            field=models.TextField(max_length=300),
        ),
    ]
