# Generated by Django 5.1.1 on 2024-10-15 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googlelocation", "0011_corporate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="corporate",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="hotels",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="publicservices",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="residentials",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="retails",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="supermarket",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
        migrations.AlterField(
            model_name="tourist",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="googlelocation.sourcelocation",
            ),
        ),
    ]
